services:
  jekyll:
    image: ruby:3.2
    command: >
      bash -c "bundle install &&
      bundle exec jekyll serve --host 0.0.0.0 --port 8001 --force_polling --livereload --drafts"
    ports:
      - "8001:8001"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
